#!/bin/bash
if [ "$(readlink "$0")" == "" ]; then
    pushd `dirname $0` > /dev/null
    export POWERTRAIN_DIR=`pwd -P`
    popd > /dev/null
else
    export POWERTRAIN_DIR=$(readlink "$0" | xargs dirname)
fi
export POWERTRAIN=$POWERTRAIN_DIR/Makefile

if [ -n "$PROJECT_DIR" ] && [ -n "$(cat $PROJECT_DIR/Makefile)" ]; then
    export PROJECT_DIR=$PROJECT_DIR
elif [ -n "$(cat $(pwd)/Makefile)" ]; then
    export PROJECT_DIR=$(pwd)
else
    export PROJECT_DIR=$POWERTRAIN_DIR
fi

#TODO take $@ search through looking for --word=something and change to WORD=something

make -C $PROJECT_DIR $@ POWERTRAIN_DIR=$POWERTRAIN_DIR PROJECT_DIR=$PROJECT_DIR
