#!/bin/bash
if [ "$(readlink "$0")" == "" ]; then
    pushd `dirname $0` > /dev/null
    export POWERTRAIN_DIR=`pwd -P`
    popd > /dev/null
else
    export POWERTRAIN_DIR=$(readlink "$0" | xargs dirname)
fi

export ENTRY_DIR=$(pwd)
export POWERTRAIN=$POWERTRAIN_DIR/powertrain.mk

if [ -n "$PT_CONTEXT" ] && cat "$PT_CONTEXT/powertrain.mk" > /dev/null 2>&1; then
    export PT_CONTEXT=$PT_CONTEXT
    FILENAME="powertrain.mk"
    printf "Using powertrain.mk from specified \$PT_CONTEXT"
elif [ -n "$PT_CONTEXT" ] && cat "$PT_CONTEXT/Makefile" > /dev/null 2>&1; then
    export PT_CONTEXT=$PT_CONTEXT
    FILENAME="Makefile"
    printf "Using Makefile from specified \$PT_CONTEXT"
elif cat $(pwd)/powertrain.mk > /dev/null 2>&1; then
    export PT_CONTEXT=$(pwd)
    FILENAME="powertrain.mk"
    printf "Using powertrain.mk from current directory"
elif cat $(pwd)/Makefile > /dev/null 2>&1; then
    export PT_CONTEXT=$(pwd)
    FILENAME="Makefile"
    printf "Using Makefile from current directory"
else
    export PT_CONTEXT=$POWERTRAIN_DIR
    printf "Using default powertrain.mk"
fi
printf " ($PT_CONTEXT/$FILENAME)\n\n"

if [ "$POWERTRAIN_DIR" == "$PT_CONTEXT" ] || [ -f "$PT_CONTEXT/Makefile" ]; then
    export HAS_OWN_MAKE=true
fi

if [ "$POWERTRAIN_DIR" != "$PT_CONTEXT" ] && [ -f "$PT_CONTEXT/Makefile" ]; then
    printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
    printf "Using custom Makefile ($PT_CONTEXT/Makefile). This functionality is deprecated. Please review the powertrain documentation and convert your Makefile to powertrain.mk.\n"
    printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\n"
fi

[ -z "$HAS_OWN_MAKE" ] && cp $POWERTRAIN_DIR/Makefile $PT_CONTEXT/Makefile && echo 'include $(PT_CONTEXT)/powertrain.mk' >> $PT_CONTEXT/Makefile
[ -z "$HAS_OWN_MAKE" ] && [ -n "$PT_CONFIG" ] && echo 'include $(PT_CONTEXT)/powertrain/$(PT_CONFIG).mk' >> $PT_CONTEXT/Makefile
[ -z "$HAS_OWN_MAKE" ] && [ -f "$PT_CONTEXT/powertrain_runtime_config.mk" ] && echo 'include $(PT_CONTEXT)/powertrain_runtime_config.mk' >> $PT_CONTEXT/Makefile
make -C $PT_CONTEXT $@ POWERTRAIN_DIR=$POWERTRAIN_DIR PT_CONTEXT=$PT_CONTEXT
[ -z "$HAS_OWN_MAKE" ] && rm $PT_CONTEXT/Makefile
